### ISSUE TITLE
Please provide support for FreePascal Compiler

### ISSUE THREAD

**Issue by roseswe** [ncs-sniper/Lib.SHA3#1]
fpc  SHA3.pas 
Linux Build
Free Pascal Compiler version 2.6.4 [2016/04/28] for x86_64
Copyright (c) 1993-2014 by Florian Klaempfl and others
Target OS: Linux for x86-64
Compiling SHA3.pas
SHA3.pas(70,69) Fatal: Syntax error, ")" expected but "=" found
Fatal: Compilation aborted
Error: /usr/bin/ppcx64 returned an error exitcode (normal if you did not specify a source file to be compiled)

**Comment by ncs-sniper** [comment]
Same situation as https://github.com/ncs-sniper/Lib.SHA2/issues/1 , this time it is default parameter. Will correct soon.

**Comment by ncs-sniper** [comment]
See https://github.com/ncs-sniper/Lib.SHA2/issues/1#issuecomment-259150776

**Comment by roseswe** [comment]
works
